deploy: 
    script: ssh 'nginx@178.172.201.122' -p1100 "cd /home/web/www/alfa.belan.by/ && git pull"

build:
    script: ssh 'nginx@178.172.201.122' -p1100 "cd /home/web/www/alfa.belan.by/ && ng build --output-path /home/web/www/alfa.belan.by/dist"
